title: Blog
description: Sharing my experiences and knowledge in DFIR,and CTF writeups while learning and growing in cybersecurity
url: "https://yourusername.github.io"

theme: minima # can override with custom CSS

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"
